name: Build/Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  build-deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: v20.9.0
          cache: "pnpm"
      - name: Setup GitHub Deploy SSH Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GH_DEPLOY_SSH_KEY }}
      - name: Build & Deploy Documentation
        run: ./SpotifyAPI.Docs/docs.sh
