name: Build/Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  build-deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - name: Build & Deploy Documentation
        run: ./SpotifyAPI.Docs/docs.sh
